on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack build
      - run: wasm-pack pack
      - run: npm set "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN"
      - run: npm set registry=https://npm.pkg.github.com
      - run: wasm-pack publish
