on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack build
      - run: wasm-pack pack .
      
      - uses: actions/upload-artifact@v4
        with:
          name: phtherichthys
          path: phtherichthys*.tgz